// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function LookupErrorMessage(arg1) {
  return window['go']['backend']['App']['LookupErrorMessage'](arg1);
}

export function OpenLinkFile(arg1) {
  return window['go']['backend']['App']['OpenLinkFile'](arg1);
}

export function ReadPaths(arg1) {
  return window['go']['backend']['App']['ReadPaths'](arg1);
}

export function SetDevToolsState(arg1) {
  return window['go']['backend']['App']['SetDevToolsState'](arg1);
}

export function StartMonitor(arg1) {
  return window['go']['backend']['App']['StartMonitor'](arg1);
}

export function StatPaths(arg1) {
  return window['go']['backend']['App']['StatPaths'](arg1);
}

export function StopMonitor() {
  return window['go']['backend']['App']['StopMonitor']();
}

export function ToggleDevTools() {
  return window['go']['backend']['App']['ToggleDevTools']();
}
