// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LookupErrorMessage(arg1:string):Promise<string>;

export function OpenLinkFile(arg1:Array<number>):Promise<backend.ReadPathsResult>;

export function ReadPaths(arg1:Array<string>):Promise<backend.ReadPathsResult>;

export function ScanFolderChanges(arg1:string,arg2:Array<string>):Promise<backend.FolderChangesResult>;

export function SetDevToolsState(arg1:boolean):Promise<void>;

export function StatPaths(arg1:Array<string>):Promise<Array<backend.PathFileStat>>;

export function ToggleDevTools():Promise<void>;
